### ISSUE TITLE
BUG: Unhandled SIGABRT for constant-valued input columns

### ISSUE THREAD

**Issue by mjbommar** [OpenMined/PipelineDP#237]
## Description
When presented with constant-valued input data, `PyDP` throws an unhandled `SIGABRT` from `differential-privacy`.  This obviously causes the whole interpreter to crash without any opportunity for "normal" exception handling.

While this might seem like a pathological data example, it may become more noticeable if users are working with convenience methods and more common datasets (e.g., with DataFrames).

PS: constant columns should at least not affect the \eps-budget as they have no mutual information/dependence :smiley: 

## How to Reproduce
1. Please see script in next comment to reproduce.  (it is more than minimum reproduction script, but it also will also be useful for next submitted issue/question)
2. 
```
$ gdb python
(gdb)  run constant_column.py
```

## Expected Behavior
An `AssertionError` prior to calling `PyDP` or some more specific exception like `ValueError` with warning about constant-valued or zero-variance mechanism/column.

## Screenshots
See `gdb run` log in next comment.

## System Information
 - OS: Ubuntu
 - OS Version: 20.04.3
 - Language Version: CPython 3.8.8
 - Package Manager Version: Poetry version 1.1.12

## Additional Context
Also shared via #differential-privacy on OpenMind slack:
https://openmined.slack.com/archives/CB4EP5D70/p1643557270033129)

**Comment by mjbommar** [comment]
* GDB Log: https://gist.github.com/mjbommar/51f140dfc05b0848c2c7a719cd822846
* constant_column.py replication script: https://gist.github.com/mjbommar/2cca12a7e0f3c8976daf0f4054bc6391

**Comment by dvadym** [comment]
FYI: [PR](https://github.com/OpenMined/PipelineDP/pull/240) to fix this issue is in code review

**Comment by dvadym** [comment]
This bug is fixed. Thanks for reporting!

@mjbommar 
I've checked [the replication script](https://gist.github.com/mjbommar/2cca12a7e0f3c8976daf0f4054bc6391)

`min_value = df[value_column_name].min() - df[value_column_name].std()` this is not-DP way to find `min_value`, `max_value`.

**Example**: let X = {1,1,1}, but X'={1,1,1,2}. 

`min_value(X)=1`
`min_value(X') ~= 0.5`

i.e. adding of one user changes min_value with 100% probability.

For achieving DP, min_value/max_value should be chosen without looking at data or with applying DP. It's not a problem if a value in data will be <min_value, in such case it will be clipped to [min_value, max_value]

We have plans to implement DP algorithm for finding min_value, max_value
