### ISSUE TITLE
Using accumulators in SparkOperations

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#41]
# Context

Currently the development of [Accumulator Framework](https://github.com/OpenMined/PipelineDP/issues/37) is in progress. The idea is that **Accumulator Framework** is independent of the pipeline framework. This issue is about implementing usage of **Accumulator Framework** with Spark.

The interface of accumulators:

```
class Accumulator(ABC):
     def merge(cls,  accumulators: Iterable[Accumulator]) -> Accumulator
     def add(v)
     def compute_metrics()
```

# Goals
To implement the following method of [SparkRDDOperations](https://github.com/OpenMined/PipelineDP/blob/65d00ee6c906a36b8a173ddbb83d7e3bf71905b4/pipeline_dp/pipeline_operations.py#L102):

`def reduce_accumulators_per_key(self, col):`

where **col** contains elements:  (key, accumulator) 

and the return is a collection of elements (key, accumulator), such that all elements per each key are merged.

# Notes
It looks like **reduce_accumulators_per_key** might be implement with usage of [reduce_by_key](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.RDD.reduceByKey.html).

**Comment by boyaryn** [comment]
Hi Vadim, I'd like to work on this.

**Comment by dvadym** [comment]
Sure, thanks!

**Comment by dvadym** [comment]
As a continuation of [discussion](https://github.com/OpenMined/PipelineDP/issues/37#issuecomment-863243045).

It looks like the `reduce_accumulators_per_key` implementation don't need ZeroAccumulator, because it receives already accumulators objects. Isn't it?

**Comment by dvadym** [comment]
The explanation about creating accumulators and zero accumulators:

[Here](https://github.com/OpenMined/PipelineDP/blob/cd491a311403918233b7234799be478e3f107061/pipeline_dp/dp_engine.py#L92) is the place when accumulators are created (inside `aggregator_fn` function). They created from list of values - so no need zero accumulators now.

The complexity with zero accumulators, that what **0** means, depends on the type of aggregation and on the parameters of aggregation in order to ensure that the result is anonymized.

E.g. 

1. dp count the **0** aggregation result should be **0 + random noise**
2. dp mean the **0** aggregation result should be **0 + random noise_1**/**0 + random noise_2**

and moreover the standard deviation of the random noise depends on parameters of DP computations.

**Comment by boyaryn** [comment]
Thanks for the explanation.

Initially I thought that mapping each value into its own accumulator should be avoided because it'd put unnecessary strain on the Garbage Collector. An alternative for creation of accumulator for each element could be creation of one 'zero' accumulator per partition, using Accumulator's `add_value(v)` to go over elements in this partition and update this accumulator object [in place](https://github.com/apache/spark/blob/3fb044e043a2feab01d79b30c25b93d4fd166b12/python/pyspark/rdd.py#L1089-L1090) for every element, and then use Accumulator's `add_accumulator(accumulator)` to merge accumulators.

After your explanation I see that this approach with zero/add_value/add_accumulator would need to make implementation of the Accumulator class capable of adding noise. For example, inside `add_value(v)`. Without performing real tests comparing speed performance of both implementation approaches, I don't know what would be best. Do you suggest sticking to the current approach for the time being? If yes, we don't even need `add_value(v)` in the Accumulator class: `reduce_accumulators_per_key` only need `add_accumulator(…)` (or `merge(…)`).

**Comment by dvadym** [comment]
`add_value` is fine, we will need it afterwards (and `add_value` isn't controversial, so no problem).

Yeah, Accumulator, more precisely DPAccumulators :) will encapsulate logic of applying Differential Privacy to aggregated data.
