### ISSUE TITLE
Implement filter_by_key in SparkRDDOperations

### ISSUE THREAD

**Issue by dvadym** [OpenMined/PipelineDP#50]
## Context

On [issue](https://github.com/OpenMined/PipelineDP/issues/4) `filter_by_key` method was implemented in [BeamOperations](https://github.com/OpenMined/PipelineDP/blob/e33a7c724179dba77b7646597f2af80e47ffe5a7/pipeline_dp/pipeline_operations.py#L118) and [LocalOperations](https://github.com/OpenMined/PipelineDP/blob/e33a7c724179dba77b7646597f2af80e47ffe5a7/pipeline_dp/pipeline_operations.py#L290).

## Goals
Implement `filter_by_key` in SparkRDDOperations with API:

`def filter_by_key(self, col, public_partitions)`

`col` is a collection (multimap) of **(partition_key, data)** (type of data is not important)
`public_partitions` is a collection of **(partition_key, )**,

`filter_by_key` returns `[record for record in collection if record[0] in public_partitions]`

1. If `public_partitions` is some Python collection then we can assume that memory is enough, Map operations is enough.
2. If `public_partitions` is RDD then join is required

## Open questions
Is it possible to unify more `filter_by_key` between `BeamOperations/SparkRDDOperations`? For example to come up with the join API in `PipelineOperations` and to implement `filter_by_key` using this API.

**Comment by boyaryn** [comment]
Hi Vadim, I'd like to work on this.

**Comment by dvadym** [comment]
Sure, thank you!

**Comment by boyaryn** [comment]
I looked at the implementation of `filter_by_key` in `BeamOperations` and Apache Beam API to think if abstracting some logic to some method in `PipelineOperations` is possible.

Although it looks possible, I'm not sure if it'd be a good solution. There are 2 issues.

The smaller one is that equivalent methods in Beam API and Spark API are called differently. In Beam, it's a new object creation with passing the previous collection to the constructor. In Spark, it's calling a method on the previous RDD. For example, `beam.CoGroupByKey(cols, "Filtering data from public partitions")` vs `rdd1.cogroup(rdd2)`. This incompatibility could be worked around by producing in `BeamOperations.filter_by_key` or `SparkRDDOperations.filter_by_key` auxiliary python constructs to be passed to `PipelineOperations.join`.

The bigger one is reliability. I'd use the `join` transformation of Spark because it may perform public partition selection even if the values corresponding to some public partition key don't feet into 1 Spark worker. [`spark.sql.autoBroadcastJoinThreshold`](https://spark.apache.org/docs/latest/sql-performance-tuning.html) defines how big the left RDD can be to be broadcast to worker nodes. If I use in `SparkRDDOperations.filter_by_key`'s implementation `cogroup` and `flatMap` as counterparts of `beam.CoGroupByKey()` and `beam.ParDo()` for the sake of conformability with `BeamOperations.filter_by_key`, such implementation would crash in case of public partitions not fitting into 1 worker.

What do you think?

**Comment by dvadym** [comment]
Thanks for investigation and explanation! I didn't know about difference between `cogroup` and `join` in Spark.

> The smaller one is that equivalent methods in Beam API and Spark API are called differently.

 That's fine, `PipelineOperations` hides that.

>  I'd use the join transformation of Spark because it may perform public partition selection even if the values corresponding to some public partition key don't feet into 1 Spark worker.

Thanks, that's a very good point! Let's use `join`. I believe here scalability is more important that unifying some logic among Beam and Spark and anyway that logic is not that complicated.

So please implement `filter_by_key` w/o any logic unifying.

**Comment by boyaryn** [comment]
Cool, I also think that unifying the logic is less important than scalability.

I've stuck to the `filter_by_key`'s signature which Lovro used while implementing `filter_by_key` for other processing engines: `filter_by_key(self, col, public_partitions, data_extractors, stage_name: str = None)`. Is this okay?
